// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package pir

import (
	"fmt"
	"strings"
)

const (
	// no operation
	NOOPE Operation = iota
	// move register byte RnL -> RmL or RnH -> RmH
	MOVRB
	// move register word RnL -> RmL or RnH -> RmH
	MOVRW
	// Get byte from address pointed by Rn to Rm
	GETRB
	// Get word from address pointed by Rn to Rm
	GETRW
	// increment register byte
	INCRB
	// increment register word
	INCRW
	// decrement register byte
	DECRB
	// decrement register word
	DECRW
	// push register word to data stack
	PUSHW
	// pop data stack word to register (there is no byte variant)
	POPRW
	// Store literal byte in register RnL or RnH
	LITRB
	// Store literal word in register RnL
	LITRW
	// Output register byte to port [int] (constant literal).
	OUTRB
	// Output register word to port [int] (constant literal).
	OUTRW
	// Output R1 must have the address, R2 the length, output to port [int]
	OUTRA
	// Input byte from port [int] to register.
	INPRB
	// Input word from port [int] to register.
	INPWB
	// Output R1 must have the address, R2 the length, input from port [int]
	INPRA
	// Name tag of next DATS, VARI, FUNC, etc instruction [ident].
	NAMET
	// Load tag address into register.
	LOADT
	// Define jump location [ident].
	LABEL
	// Jump to tag [ident] unconditionally.
	JUMPT
	// Jump on [cond] to tag [ident] it TOS is TRUE, pop stack.
	JPIFT
	// Ident is one of [eq, gt, lt, etc], compare register with R1L and store in R1L.
	CONDB
	// Data String.
	DATAS
	// Inline assembly string.
	IASMS
	// Add byte Rn to Rm and store in Rm
	ADDRB
	// Add word Rn to Rm and store in Rm
	ADDRW
	// Subtract byte Rn from Rm and store in Rm
	SUBRB
	// Subtract word Rn from Rm and store in Rm
	SUBRW
	// AND byte Rn with Rm and store in Rm
	ANDRB
	// AND word Rn with Rm and store in Rm
	ANDRW
	// Binary OR byte Rn with Rm and store in Rm
	BORRB
	// Binary OR word Rn with Rm and store in Rm
	BORRW
	// Binary XOR byte Rn with Rm and store in Rm
	XORRB
	// Binary XOR word Rn with Rm and store in Rm
	XORRW
	// Shift left by Int to byte register.
	SHLRB
	// Shift left by Int to word register.
	SHLRW
	// Shift right by Int to byte register.
	SHRRB
	// Shift right by Int to word register.
	SHRRW
	// Store register to temporary Rn to Tn. There is no byte variant.
	STORT
	// Get temporary to register. There is no byte variant.
	GETTR
	// Call tag.
	CALLT
	// Return normally from a call.
	RETRN
	// Return from an interrupt call.
	RETIN
	// Return from an nmi call.
	RETNM
	// Set tag as an interrupt handler.
	INTRT
	// Set tag an an NMI handler.
	NMIHT
	// Copy R2 length bytes to R1. XXX: better ideas.
	COPYR
	// Switch active memory bank to constant int.
	BANKI
	// Switch battery backed memory on or off and store address in R.
	BATER
)

var ErrInvalidOperation = fmt.Errorf("not a valid Operation, try [%s]", strings.Join(_OperationNames, ", "))

const _OperationName = "NOOPEMOVRBMOVRWGETRBGETRWINCRBINCRWDECRBDECRWPUSHWPOPRWLITRBLITRWOUTRBOUTRWOUTRAINPRBINPWBINPRANAMETLOADTLABELJUMPTJPIFTCONDBDATASIASMSADDRBADDRWSUBRBSUBRWANDRBANDRWBORRBBORRWXORRBXORRWSHLRBSHLRWSHRRBSHRRWSTORTGETTRCALLTRETRNRETINRETNMINTRTNMIHTCOPYRBANKIBATER"

var _OperationNames = []string{
	_OperationName[0:5],
	_OperationName[5:10],
	_OperationName[10:15],
	_OperationName[15:20],
	_OperationName[20:25],
	_OperationName[25:30],
	_OperationName[30:35],
	_OperationName[35:40],
	_OperationName[40:45],
	_OperationName[45:50],
	_OperationName[50:55],
	_OperationName[55:60],
	_OperationName[60:65],
	_OperationName[65:70],
	_OperationName[70:75],
	_OperationName[75:80],
	_OperationName[80:85],
	_OperationName[85:90],
	_OperationName[90:95],
	_OperationName[95:100],
	_OperationName[100:105],
	_OperationName[105:110],
	_OperationName[110:115],
	_OperationName[115:120],
	_OperationName[120:125],
	_OperationName[125:130],
	_OperationName[130:135],
	_OperationName[135:140],
	_OperationName[140:145],
	_OperationName[145:150],
	_OperationName[150:155],
	_OperationName[155:160],
	_OperationName[160:165],
	_OperationName[165:170],
	_OperationName[170:175],
	_OperationName[175:180],
	_OperationName[180:185],
	_OperationName[185:190],
	_OperationName[190:195],
	_OperationName[195:200],
	_OperationName[200:205],
	_OperationName[205:210],
	_OperationName[210:215],
	_OperationName[215:220],
	_OperationName[220:225],
	_OperationName[225:230],
	_OperationName[230:235],
	_OperationName[235:240],
	_OperationName[240:245],
	_OperationName[245:250],
	_OperationName[250:255],
	_OperationName[255:260],
}

// OperationNames returns a list of possible string values of Operation.
func OperationNames() []string {
	tmp := make([]string, len(_OperationNames))
	copy(tmp, _OperationNames)
	return tmp
}

var _OperationMap = map[Operation]string{
	NOOPE: _OperationName[0:5],
	MOVRB: _OperationName[5:10],
	MOVRW: _OperationName[10:15],
	GETRB: _OperationName[15:20],
	GETRW: _OperationName[20:25],
	INCRB: _OperationName[25:30],
	INCRW: _OperationName[30:35],
	DECRB: _OperationName[35:40],
	DECRW: _OperationName[40:45],
	PUSHW: _OperationName[45:50],
	POPRW: _OperationName[50:55],
	LITRB: _OperationName[55:60],
	LITRW: _OperationName[60:65],
	OUTRB: _OperationName[65:70],
	OUTRW: _OperationName[70:75],
	OUTRA: _OperationName[75:80],
	INPRB: _OperationName[80:85],
	INPWB: _OperationName[85:90],
	INPRA: _OperationName[90:95],
	NAMET: _OperationName[95:100],
	LOADT: _OperationName[100:105],
	LABEL: _OperationName[105:110],
	JUMPT: _OperationName[110:115],
	JPIFT: _OperationName[115:120],
	CONDB: _OperationName[120:125],
	DATAS: _OperationName[125:130],
	IASMS: _OperationName[130:135],
	ADDRB: _OperationName[135:140],
	ADDRW: _OperationName[140:145],
	SUBRB: _OperationName[145:150],
	SUBRW: _OperationName[150:155],
	ANDRB: _OperationName[155:160],
	ANDRW: _OperationName[160:165],
	BORRB: _OperationName[165:170],
	BORRW: _OperationName[170:175],
	XORRB: _OperationName[175:180],
	XORRW: _OperationName[180:185],
	SHLRB: _OperationName[185:190],
	SHLRW: _OperationName[190:195],
	SHRRB: _OperationName[195:200],
	SHRRW: _OperationName[200:205],
	STORT: _OperationName[205:210],
	GETTR: _OperationName[210:215],
	CALLT: _OperationName[215:220],
	RETRN: _OperationName[220:225],
	RETIN: _OperationName[225:230],
	RETNM: _OperationName[230:235],
	INTRT: _OperationName[235:240],
	NMIHT: _OperationName[240:245],
	COPYR: _OperationName[245:250],
	BANKI: _OperationName[250:255],
	BATER: _OperationName[255:260],
}

// String implements the Stringer interface.
func (x Operation) String() string {
	if str, ok := _OperationMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Operation(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Operation) IsValid() bool {
	_, ok := _OperationMap[x]
	return ok
}

var _OperationValue = map[string]Operation{
	_OperationName[0:5]:     NOOPE,
	_OperationName[5:10]:    MOVRB,
	_OperationName[10:15]:   MOVRW,
	_OperationName[15:20]:   GETRB,
	_OperationName[20:25]:   GETRW,
	_OperationName[25:30]:   INCRB,
	_OperationName[30:35]:   INCRW,
	_OperationName[35:40]:   DECRB,
	_OperationName[40:45]:   DECRW,
	_OperationName[45:50]:   PUSHW,
	_OperationName[50:55]:   POPRW,
	_OperationName[55:60]:   LITRB,
	_OperationName[60:65]:   LITRW,
	_OperationName[65:70]:   OUTRB,
	_OperationName[70:75]:   OUTRW,
	_OperationName[75:80]:   OUTRA,
	_OperationName[80:85]:   INPRB,
	_OperationName[85:90]:   INPWB,
	_OperationName[90:95]:   INPRA,
	_OperationName[95:100]:  NAMET,
	_OperationName[100:105]: LOADT,
	_OperationName[105:110]: LABEL,
	_OperationName[110:115]: JUMPT,
	_OperationName[115:120]: JPIFT,
	_OperationName[120:125]: CONDB,
	_OperationName[125:130]: DATAS,
	_OperationName[130:135]: IASMS,
	_OperationName[135:140]: ADDRB,
	_OperationName[140:145]: ADDRW,
	_OperationName[145:150]: SUBRB,
	_OperationName[150:155]: SUBRW,
	_OperationName[155:160]: ANDRB,
	_OperationName[160:165]: ANDRW,
	_OperationName[165:170]: BORRB,
	_OperationName[170:175]: BORRW,
	_OperationName[175:180]: XORRB,
	_OperationName[180:185]: XORRW,
	_OperationName[185:190]: SHLRB,
	_OperationName[190:195]: SHLRW,
	_OperationName[195:200]: SHRRB,
	_OperationName[200:205]: SHRRW,
	_OperationName[205:210]: STORT,
	_OperationName[210:215]: GETTR,
	_OperationName[215:220]: CALLT,
	_OperationName[220:225]: RETRN,
	_OperationName[225:230]: RETIN,
	_OperationName[230:235]: RETNM,
	_OperationName[235:240]: INTRT,
	_OperationName[240:245]: NMIHT,
	_OperationName[245:250]: COPYR,
	_OperationName[250:255]: BANKI,
	_OperationName[255:260]: BATER,
}

// ParseOperation attempts to convert a string to a Operation.
func ParseOperation(name string) (Operation, error) {
	if x, ok := _OperationValue[name]; ok {
		return x, nil
	}
	return Operation(0), fmt.Errorf("%s is %w", name, ErrInvalidOperation)
}

// MarshalText implements the text marshaller method.
func (x Operation) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Operation) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOperation(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Operation) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
