// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package pir

import (
	"fmt"
	"strings"
)

const (
	// no operation
	NOOP Operation = iota
	// increment stop of stack byte
	INCB
	// increment stop of stack word
	INCW
	// increment stop of stack byte
	DECB
	// increment stop of stack word
	DECW
	// Drop byte from data stack
	POPB
	// Drop word from data stack
	POPW
	// Duplicate byte on top of stack
	DUPB
	// Duplicate word on top of stack
	DUPW
	// Duplicate word on next of stack to top of stack
	NXTW
	// Push byte literal [byte] to data stack.
	PSHB
	// Push word literal [word] to data stack.
	PSHW
	// Push address of [ident] to data stack.
	PSHA
	// Output TOS byte to port [int] (constant literal) and pop.
	OUTB
	// Output TOS word to port [int] (constant literal) and pop.
	OUTW
	// Output TOS address, length NXT bytes to port [int] (constant literal) and pop twice.
	OUTA
	// Input byte from port [int], push to stack.
	INPB
	// Input word from port [int], push to stack.
	INPW
	// Name tag of next DATS, VARI, FUNC, etc instruction [ident].
	NAME
	// Push address of tag [ident] to data stack.
	PSHT
	// Define jump location [ident].
	LABL
	// Jump to tag [ident] unconditionally.
	JUMP
	// Jump to tag [ident] it TOS is TRUE, pop stack.
	JPIF
	// Ident is one of [eq, gt, lt, etc], compare and push boolean to TOS.
	COND
	// Data String
	DATS
	IASM
	ADDB
	ADDW
	SUBB
	SUBW
	ANDB
	ANDW
	BORB
	BORW
	XORB
	XORW
	SHLB
	SHLW
	SHRB
	SHRW
	GETB
)

var ErrInvalidOperation = fmt.Errorf("not a valid Operation, try [%s]", strings.Join(_OperationNames, ", "))

const _OperationName = "NOOPINCBINCWDECBDECWPOPBPOPWDUPBDUPWNXTWPSHBPSHWPSHAOUTBOUTWOUTAINPBINPWNAMEPSHTLABLJUMPJPIFCONDDATSIASMADDBADDWSUBBSUBWANDBANDWBORBBORWXORBXORWSHLBSHLWSHRBSHRWGETB"

var _OperationNames = []string{
	_OperationName[0:4],
	_OperationName[4:8],
	_OperationName[8:12],
	_OperationName[12:16],
	_OperationName[16:20],
	_OperationName[20:24],
	_OperationName[24:28],
	_OperationName[28:32],
	_OperationName[32:36],
	_OperationName[36:40],
	_OperationName[40:44],
	_OperationName[44:48],
	_OperationName[48:52],
	_OperationName[52:56],
	_OperationName[56:60],
	_OperationName[60:64],
	_OperationName[64:68],
	_OperationName[68:72],
	_OperationName[72:76],
	_OperationName[76:80],
	_OperationName[80:84],
	_OperationName[84:88],
	_OperationName[88:92],
	_OperationName[92:96],
	_OperationName[96:100],
	_OperationName[100:104],
	_OperationName[104:108],
	_OperationName[108:112],
	_OperationName[112:116],
	_OperationName[116:120],
	_OperationName[120:124],
	_OperationName[124:128],
	_OperationName[128:132],
	_OperationName[132:136],
	_OperationName[136:140],
	_OperationName[140:144],
	_OperationName[144:148],
	_OperationName[148:152],
	_OperationName[152:156],
	_OperationName[156:160],
	_OperationName[160:164],
}

// OperationNames returns a list of possible string values of Operation.
func OperationNames() []string {
	tmp := make([]string, len(_OperationNames))
	copy(tmp, _OperationNames)
	return tmp
}

var _OperationMap = map[Operation]string{
	NOOP: _OperationName[0:4],
	INCB: _OperationName[4:8],
	INCW: _OperationName[8:12],
	DECB: _OperationName[12:16],
	DECW: _OperationName[16:20],
	POPB: _OperationName[20:24],
	POPW: _OperationName[24:28],
	DUPB: _OperationName[28:32],
	DUPW: _OperationName[32:36],
	NXTW: _OperationName[36:40],
	PSHB: _OperationName[40:44],
	PSHW: _OperationName[44:48],
	PSHA: _OperationName[48:52],
	OUTB: _OperationName[52:56],
	OUTW: _OperationName[56:60],
	OUTA: _OperationName[60:64],
	INPB: _OperationName[64:68],
	INPW: _OperationName[68:72],
	NAME: _OperationName[72:76],
	PSHT: _OperationName[76:80],
	LABL: _OperationName[80:84],
	JUMP: _OperationName[84:88],
	JPIF: _OperationName[88:92],
	COND: _OperationName[92:96],
	DATS: _OperationName[96:100],
	IASM: _OperationName[100:104],
	ADDB: _OperationName[104:108],
	ADDW: _OperationName[108:112],
	SUBB: _OperationName[112:116],
	SUBW: _OperationName[116:120],
	ANDB: _OperationName[120:124],
	ANDW: _OperationName[124:128],
	BORB: _OperationName[128:132],
	BORW: _OperationName[132:136],
	XORB: _OperationName[136:140],
	XORW: _OperationName[140:144],
	SHLB: _OperationName[144:148],
	SHLW: _OperationName[148:152],
	SHRB: _OperationName[152:156],
	SHRW: _OperationName[156:160],
	GETB: _OperationName[160:164],
}

// String implements the Stringer interface.
func (x Operation) String() string {
	if str, ok := _OperationMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Operation(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Operation) IsValid() bool {
	_, ok := _OperationMap[x]
	return ok
}

var _OperationValue = map[string]Operation{
	_OperationName[0:4]:     NOOP,
	_OperationName[4:8]:     INCB,
	_OperationName[8:12]:    INCW,
	_OperationName[12:16]:   DECB,
	_OperationName[16:20]:   DECW,
	_OperationName[20:24]:   POPB,
	_OperationName[24:28]:   POPW,
	_OperationName[28:32]:   DUPB,
	_OperationName[32:36]:   DUPW,
	_OperationName[36:40]:   NXTW,
	_OperationName[40:44]:   PSHB,
	_OperationName[44:48]:   PSHW,
	_OperationName[48:52]:   PSHA,
	_OperationName[52:56]:   OUTB,
	_OperationName[56:60]:   OUTW,
	_OperationName[60:64]:   OUTA,
	_OperationName[64:68]:   INPB,
	_OperationName[68:72]:   INPW,
	_OperationName[72:76]:   NAME,
	_OperationName[76:80]:   PSHT,
	_OperationName[80:84]:   LABL,
	_OperationName[84:88]:   JUMP,
	_OperationName[88:92]:   JPIF,
	_OperationName[92:96]:   COND,
	_OperationName[96:100]:  DATS,
	_OperationName[100:104]: IASM,
	_OperationName[104:108]: ADDB,
	_OperationName[108:112]: ADDW,
	_OperationName[112:116]: SUBB,
	_OperationName[116:120]: SUBW,
	_OperationName[120:124]: ANDB,
	_OperationName[124:128]: ANDW,
	_OperationName[128:132]: BORB,
	_OperationName[132:136]: BORW,
	_OperationName[136:140]: XORB,
	_OperationName[140:144]: XORW,
	_OperationName[144:148]: SHLB,
	_OperationName[148:152]: SHLW,
	_OperationName[152:156]: SHRB,
	_OperationName[156:160]: SHRW,
	_OperationName[160:164]: GETB,
}

// ParseOperation attempts to convert a string to a Operation.
func ParseOperation(name string) (Operation, error) {
	if x, ok := _OperationValue[name]; ok {
		return x, nil
	}
	return Operation(0), fmt.Errorf("%s is %w", name, ErrInvalidOperation)
}

// MarshalText implements the text marshaller method.
func (x Operation) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Operation) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOperation(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Operation) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
