// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package pir

import (
	"errors"
	"fmt"
)

const (
	// KindNone is a Kind of type None.
	// No operand, skipped.
	KindNone Kind = iota
	// KindByte is a Kind of type Byte.
	KindByte
	// KindWord is a Kind of type Word.
	KindWord
	// KindInt is a Kind of type Int.
	KindInt
	// KindIdent is a Kind of type Ident.
	KindIdent
	// KindString is a Kind of type String.
	KindString
	// KindRegister is a Kind of type Register.
	KindRegister
	// KindTemporary is a Kind of type Temporary.
	KindTemporary
	// KindCondition is a Kind of type Condition.
	KindCondition
	// KindHalf is a Kind of type Half.
	KindHalf
)

var ErrInvalidKind = errors.New("not a valid Kind")

const _KindName = "NoneByteWordIntIdentStringRegisterTemporaryConditionHalf"

var _KindMap = map[Kind]string{
	KindNone:      _KindName[0:4],
	KindByte:      _KindName[4:8],
	KindWord:      _KindName[8:12],
	KindInt:       _KindName[12:15],
	KindIdent:     _KindName[15:20],
	KindString:    _KindName[20:26],
	KindRegister:  _KindName[26:34],
	KindTemporary: _KindName[34:43],
	KindCondition: _KindName[43:52],
	KindHalf:      _KindName[52:56],
}

// String implements the Stringer interface.
func (x Kind) String() string {
	if str, ok := _KindMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Kind(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Kind) IsValid() bool {
	_, ok := _KindMap[x]
	return ok
}

var _KindValue = map[string]Kind{
	_KindName[0:4]:   KindNone,
	_KindName[4:8]:   KindByte,
	_KindName[8:12]:  KindWord,
	_KindName[12:15]: KindInt,
	_KindName[15:20]: KindIdent,
	_KindName[20:26]: KindString,
	_KindName[26:34]: KindRegister,
	_KindName[34:43]: KindTemporary,
	_KindName[43:52]: KindCondition,
	_KindName[52:56]: KindHalf,
}

// ParseKind attempts to convert a string to a Kind.
func ParseKind(name string) (Kind, error) {
	if x, ok := _KindValue[name]; ok {
		return x, nil
	}
	return Kind(0), fmt.Errorf("%s is %w", name, ErrInvalidKind)
}

// MarshalText implements the text marshaller method.
func (x Kind) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Kind) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseKind(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Kind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
