// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package pir

import (
	"errors"
	"fmt"
)

const (
	// OperandNone is a Operand of type None.
	OperandNone Operand = iota
	// OperandByte is a Operand of type Byte.
	OperandByte
	// OperandWord is a Operand of type Word.
	OperandWord
	// OperandInt is a Operand of type Int.
	OperandInt
	// OperandIdent is a Operand of type Ident.
	OperandIdent
	// OperandString is a Operand of type String.
	OperandString
	// OperandRegister is a Operand of type Register.
	OperandRegister
	// OperandTemporary is a Operand of type Temporary.
	OperandTemporary
)

var ErrInvalidOperand = errors.New("not a valid Operand")

const _OperandName = "NoneByteWordIntIdentStringRegisterTemporary"

var _OperandMap = map[Operand]string{
	OperandNone:      _OperandName[0:4],
	OperandByte:      _OperandName[4:8],
	OperandWord:      _OperandName[8:12],
	OperandInt:       _OperandName[12:15],
	OperandIdent:     _OperandName[15:20],
	OperandString:    _OperandName[20:26],
	OperandRegister:  _OperandName[26:34],
	OperandTemporary: _OperandName[34:43],
}

// String implements the Stringer interface.
func (x Operand) String() string {
	if str, ok := _OperandMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Operand(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Operand) IsValid() bool {
	_, ok := _OperandMap[x]
	return ok
}

var _OperandValue = map[string]Operand{
	_OperandName[0:4]:   OperandNone,
	_OperandName[4:8]:   OperandByte,
	_OperandName[8:12]:  OperandWord,
	_OperandName[12:15]: OperandInt,
	_OperandName[15:20]: OperandIdent,
	_OperandName[20:26]: OperandString,
	_OperandName[26:34]: OperandRegister,
	_OperandName[34:43]: OperandTemporary,
}

// ParseOperand attempts to convert a string to a Operand.
func ParseOperand(name string) (Operand, error) {
	if x, ok := _OperandValue[name]; ok {
		return x, nil
	}
	return Operand(0), fmt.Errorf("%s is %w", name, ErrInvalidOperand)
}

// MarshalText implements the text marshaller method.
func (x Operand) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Operand) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOperand(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Operand) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
